CREATE TABLE permisos(
id INT AUTO_INCREMENT,

nombre enum(
    "CREAR_TAREAS",    
    "EDITAR_TAREAS",    
    "ELIMINAR_TAREAS",    
    "ASIGNAR_TAREAS",    
    "CAMBIAR_ESTADO_TAREAS",
    "REPORTES",
    "ADMINISTRACIÓN_USUARIOS"
),
descripcion VARCHAR(100),
fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id));

INSERT INTO permisos(nombre) VALUES 
    ("CREAR_TAREAS"),
    ("EDITAR_TAREAS"),
    ("ELIMINAR_TAREAS"),
    ("ASIGNAR_TAREAS"),
    ("CAMBIAR_ESTADO_TAREAS"),
    ("REPORTES"),
    ("ADMINISTRACIÓN_USUARIOS"); 


INSERT INTO permisos(nombre) VALUES 
    ("EDITAR_TAREAS"),
    ("ELIMINAR_TAREAS"),
    ("ASIGNAR_TAREAS"),
    ("CAMBIAR_ESTADO_TAREAS"),
    ("REPORTES"),
    ("ADMINISTRACIÓN_USUARIOS"); 